### PR TITLE
chore: use Google-specific endpoint

### PR DESCRIPTION
**Pull request by olavloite**
cc @thiagotnunes

### CODE REVIEW

**Comment by thiagotnunes** [comment]
Don't we need to add a `distribution-management` configuration to the samples as well?

**Comment by olavloite** [comment]
> Don't we need to add a `distribution-management` configuration to the samples as well?

We currently don't publish the samples in Maven Central, so we currently do not need one. I also don't think there's very much additional value in publishing these samples in Maven, as it is not something that you would add as a dependency to any other project.

**Comment by thiagotnunes** [comment]
Thanks for the explanation @olavloite, it seems we did publish them some time ago (see https://mvnrepository.com/artifact/com.google.cloudspannerecosystem/spanner-change-publisher-samples and https://mvnrepository.com/artifact/com.google.cloudspannerecosystem/spanner-change-watcher-samples). Did we stop publishing them recently?

**Comment by olavloite** [comment]
Hmm... I didn't realize that, but apparently the samples are automatically published to Maven together with the actual library, because the sample projects are added as modules to the base pom.xml [here](https://github.com/cloudspannerecosystem/spanner-change-watcher/blob/abbf3faadae0714f6b5ad24c4905aac9965f176b/pom.xml#L138). So that means that:
1. We are publishing the samples as well as the library (we could maybe opt to change that in a separate PR)
2. The samples will use the same distribution management settings as the base library, as they all share the same base pom.

**Comment by thiagotnunes** [comment]
Thanks, so this one looks good for now

**Review by thiagotnunes — APPROVED** [review]

**Pull request merged**
